backend/controllers/DashboardController.php
<?php
namespace backend\controllers;

use yii\filters\AccessControl;
use yii\web\Controller;

class DashboardController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return in_array(\Yii::$app->getUser()->getIdentity()->role, \common\models\User::$rolesBackend, true);
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * @return mixed
     * @throws \yii\base\InvalidParamException
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}

common/controllers/AuthController.php
<?php

namespace common\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use common\helpers\StringHelper;
use common\models\User;
use common\models\LoginForm;
use common\models\PasswordNewRequestForm;

class AuthController extends Controller
{
    /**
     * @var string|array
     */
    protected static $urlAfterConfirm = '/';

    /**
     * @param null|string $redirect
     * @return \yii\web\Response
     */
    public function actionLogout($redirect = null)
    {
        $user = Yii::$app->getUser();
        if (!$user->getIsGuest()) {
            $user->logout();
        }

        return $this->goBack($redirect);
    }

    /**
     * @return string|\yii\web\Response
     * @throws \yii\base\InvalidParamException
     */
    public function actionLogin()
    {
        $model = new LoginForm();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @return string|\yii\web\Response
     * @throws \yii\base\InvalidParamException
     * @throws \yii\base\InvalidConfigException
     * @throws \yii\base\Exception
     */
    public function actionRequestPasswordNew()
    {
        $model = new PasswordNewRequestForm();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', Yii::t('common', 'Further instructions sent to your email.'));

                return $this->redirect(['auth/login']);
            } else {
                //TODO: this message should be sent to the render (by validation error?), it's not necessary to do this through the session
                Yii::$app->getSession()->setFlash('error', Yii::t('common', 'Email send failed. Please try again later.'));
            }
        }

        return $this->render('requestPasswordNew', [
            'model' => $model,
        ]);
    }

    /**
     * @param string $token
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     * @throws \yii\base\Exception
     */
    public function actionConfirm($token)
    {
        $user = User::find()->where([User::COLUMN_TOKEN => $token])->andWhere('password_hash IS NOT NULL')->one();
        if ($user === null) {
            throw new NotFoundHttpException(Yii::t('common', 'User with this token is not found.'));
        }

        $password = StringHelper::generateRememberedString();

        $user->setPassword($password);
        $user->generateAuthKey();
        if ($user->role === 'guest' || $user->role === 'registered') {
            $user->role = 'verified';
        }
        $user->save(false);

        $app = Yii::$app;
        $app->getUser()->login($user);

        if ($app->getMailer()
            ->compose(
                [
                    'html' => 'authConfirm-html',
                    'text' => 'authConfirm-text',
                ],
                [
                    'username' => $user->title,
                    'password' => $password,
                    'showFrontendProfile' => true,
                ]
            )
            ->setTo($user->email)
            ->setSubject(Yii::t('common', 'Password'))
            ->send()
        ) {
            $app->getSession()->setFlash('success', Yii::t('common', 'Your password sent to the email.'));
        } else {
            $app->getSession()->setFlash('warning', Yii::t('common', 'Email with password send failed. You can set a new one or try to request again.'));
        }

        return $this->redirect(static::$urlAfterConfirm);
    }
}

backend/views/layouts/main.php
<?php

/**
 * @var $this \yii\web\View
 * @var $content string
 */

use backend\assets\AppAsset;
use yii\bootstrap\NavBar;
use common\models\User;
use common\helpers\Url;
use common\helpers\Html;
use backend\widgets\NavActiveByController;
use backend\widgets\Alert;

AppAsset::register($this);

$this->beginPage();
?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language; ?>">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="theme-color" content="#000000"/>
    <link rel="icon" type="image/png" sizes="192x192" href="<?= Url::to('@web/icon-192x192.png', true); ?>"/>
    <link rel="icon" type="image/x-icon" href="<?= Url::to('@web/favicon.ico', true); ?>" />
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta charset="<?= Yii::$app->charset; ?>"/>
    <title><?= Html::encode($this->title); ?></title>
    <?php $this->head(); ?>
    <?= Html::csrfMetaTags(); ?>
</head>
<body>
<?php $this->beginBody(); ?>

<div class="non-footer">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::t('common', 'To site'),
        'brandUrl' => Yii::$app->frontendUrlManager->getHostInfo(),
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    $user = Yii::$app->getUser();
    $isGuest = $user->getIsGuest();

    $menuItems = [];
    if ($isGuest) {
        $menuItems[] = ['label' => Yii::t('common', 'Login'), 'url' => $user->loginUrl];
    } else {
        $menuItems[] = [
            'label' => $user->getIdentity()->title,
            'items' => [
                ['label' => Yii::t('common', 'Logout'), 'url' => ['auth/logout']],
            ],
        ];
    }
    echo NavActiveByController::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);

    if (!$isGuest && in_array($user->getIdentity()->role, User::$rolesBackend, true)) {
        echo NavActiveByController::widget([
            'options' => ['class' => 'navbar-nav navbar-left'],
            'items' => [
                ['label' => Yii::t('common', 'Dashboard'), 'url' => ['dashboard/index']],
                ['label' => Yii::t('common', 'Users'    ), 'url' => ['user/index']],
            ],
        ]);
    }

    NavBar::end();
    ?>

    <div class="container">
        <?= Alert::widget(); ?>
        <?= $content; ?>
    </div>
</div>

<footer class="navbar navbar-default">
    <div class="container">
        <p class="navbar-text pull-left">© <?= Yii::$app->params['brandName']; ?>, 2014–<?= date('Y'); ?></p>

        <p class="navbar-text pull-right"><?= Html::mailto(Yii::$app->params['emailSupport']); ?></p>
    </div>
</footer>

<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>